/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { ClinicInformation } from './ClinicInformation.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ClinicInformationService } from './ClinicInformation.service';
import { ClinicInformationController } from './ClinicInformation.controller';

@Module({
  imports: [TypeOrmModule.forFeature([ClinicInformation])],
  providers: [ClinicInformationService],
  exports: [ClinicInformationService],
  controllers: [ClinicInformationController],
})
export class ClinicInformationModule {}
