/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Notes } from './Notes.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { NotesService } from './Notes.service';
import { NotesController } from './Notes.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Notes])],
  providers: [NotesService],
  exports: [NotesService],
  controllers: [NotesController],
})
export class NotesModule {}
