import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class ClinicInformationCreate {
  @ApiProperty()
  title: string;
  @ApiProperty()
  employeeNumber: string;
  @ApiProperty()
  npiNumber: string;
  @ApiProperty()
  department: string;
  @ApiProperty()
  supervisor: string;
  @ApiProperty()
  dateHired: string;
  @ApiProperty()
  dateTerminated: string;
}

export class ClinicInformation {
  @ApiProperty()
  id: number;
  @ApiProperty()
  title: string;
  @ApiProperty()
  employeeNumber: string;
  @ApiProperty()
  npiNumber: string;
  @ApiProperty()
  department: string;
  @ApiProperty()
  supervisor: string;
  @ApiProperty()
  dateHired: string;
  @ApiProperty()
  dateTerminated: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
