import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */
import * as enums from '../../enums';

export class ClientCreate {
  @ApiProperty()
  firstName: string;
  @ApiProperty()
  lastName: string;
  @ApiProperty()
  dateOfBirth: string;
  @ApiProperty()
  parentEmail: string;
  @ApiProperty()
  thingsToLookOutFor: string;
  @ApiProperty()
  status: enums.ClientStatusEnum;
}

export class Client {
  @ApiProperty()
  id: number;
  @ApiProperty()
  firstName: string;
  @ApiProperty()
  lastName: string;
  @ApiProperty()
  dateOfBirth: string;
  @ApiProperty()
  parentEmail: string;
  @ApiProperty()
  thingsToLookOutFor: string;
  @ApiProperty()
  status: enums.ClientStatusEnum;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
