service: apso-service-template

provider:
  name: aws
  runtime: nodejs20.x
  stage: local
  region: us-west-2
  environment:
    DATABASE_HOST: localhost
    DATABASE_PORT: 54322
    DATABASE_USERNAME: apso
    DATABASE_PASSWORD: password
    DATABASE_NAME: apso
    DATABASE_SCHEMA: apso_test
    DATABASE_SYNC: false
    DATABASE_LOGGING: all

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline 