import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */
import * as enums from '../../enums';

export class CredentialCreate {
  @ApiProperty()
  credentialName: enums.CredentialCredentialNameEnum;
  @ApiProperty()
  issueDate: string;
  @ApiProperty()
  expireDate: string;
  @ApiProperty()
  note: string;
  @ApiProperty()
  userId: number;
}

export class Credential {
  @ApiProperty()
  id: number;
  @ApiProperty()
  credentialName: enums.CredentialCredentialNameEnum;
  @ApiProperty()
  issueDate: string;
  @ApiProperty()
  expireDate: string;
  @ApiProperty()
  note: string;
  @ApiProperty()
  userId: number;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
