import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class SpecialConditionCreate {
  @ApiProperty()
  condition: string;
}

export class SpecialCondition {
  @ApiProperty()
  id: number;
  @ApiProperty()
  condition: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
