/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import { Client, ClientCreate } from './dtos/Client.dto';
import { ClientService } from './Client.service';

@Crud({
  model: {
    type: Client,
  },
  dto: {
    create: ClientCreate,
    update: Client,
    replace: Client,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
    join: {
      associatedStaffs: { eager: false },
      'associatedStaffs.notes': { eager: false },
      'associatedStaffs.notes.user': { eager: false },
      'associatedStaffs.notes.user.staffHour': { eager: false },
      'associatedStaffs.notes.user.clinicInformation': { eager: false },
      'associatedStaffs.notes.user.emergencyContacts': { eager: false },
      'associatedStaffs.notes.user.specialConditions': { eager: false },
      'associatedStaffs.notes.user.credentials': { eager: false },
      'associatedStaffs.staffHour': { eager: false },
      'associatedStaffs.clinicInformation': { eager: false },
      'associatedStaffs.emergencyContacts': { eager: false },
      'associatedStaffs.emergencyContacts.user': { eager: false },
      'associatedStaffs.emergencyContacts.user.notes': { eager: false },
      'associatedStaffs.emergencyContacts.user.staffHour': { eager: false },
      'associatedStaffs.emergencyContacts.user.clinicInformation': {
        eager: false,
      },
      'associatedStaffs.emergencyContacts.user.specialConditions': {
        eager: false,
      },
      'associatedStaffs.emergencyContacts.user.credentials': { eager: false },
      'associatedStaffs.specialConditions': { eager: false },
      'associatedStaffs.credentials': { eager: false },
      'associatedStaffs.credentials.user': { eager: false },
      'associatedStaffs.credentials.user.notes': { eager: false },
      'associatedStaffs.credentials.user.staffHour': { eager: false },
      'associatedStaffs.credentials.user.clinicInformation': { eager: false },
      'associatedStaffs.credentials.user.emergencyContacts': { eager: false },
      'associatedStaffs.credentials.user.specialConditions': { eager: false },
    },
  },
})
@Controller('Clients')
@ApiTags('Clients')
export class ClientController implements CrudController<Client> {
  constructor(public service: ClientService) {}

  get base(): CrudController<Client> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple Clients' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single Client' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single Client' })
  @ApiBody({
    type: ClientCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: Client) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multipleClients' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<Client>
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single Client' })
  update(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: Client) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single Client' })
  replace(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: Client) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single Client' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
