/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Client } from './Client.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ClientService } from './Client.service';
import { ClientController } from './Client.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Client])],
  providers: [ClientService],
  exports: [ClientService],
  controllers: [ClientController],
})
export class ClientModule {}
