/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import {
  EmergencyContact,
  EmergencyContactCreate,
} from './dtos/EmergencyContact.dto';
import { EmergencyContactController } from './EmergencyContact.controller';
import { EmergencyContactService } from './EmergencyContact.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('EmergencyContactController', () => {
  let controller: EmergencyContactController;
  let spyService: EmergencyContactService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: EmergencyContactService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [EmergencyContactController],
      providers: [EmergencyContactService, ApiServiceProvider],
    }).compile();

    controller = module.get<EmergencyContactController>(
      EmergencyContactController
    );
    spyService = module.get<EmergencyContactService>(EmergencyContactService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call EmergencyContactController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call EmergencyContactController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new EmergencyContact();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
