/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import {
  EmergencyContact,
  EmergencyContactCreate,
} from './dtos/EmergencyContact.dto';
import { EmergencyContactService } from './EmergencyContact.service';

@Crud({
  model: {
    type: EmergencyContact,
  },
  dto: {
    create: EmergencyContactCreate,
    update: EmergencyContact,
    replace: EmergencyContact,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
    join: {
      user: { eager: false },
      'user.notes': { eager: false },
      'user.clients': { eager: false },
      'user.clients.associatedStaffs': { eager: false },
      'user.clients.associatedStaffs.notes': { eager: false },
      'user.clients.associatedStaffs.staffHour': { eager: false },
      'user.clients.associatedStaffs.clinicInformation': { eager: false },
      'user.clients.associatedStaffs.specialConditions': { eager: false },
      'user.clients.associatedStaffs.credentials': { eager: false },
      'user.staffHour': { eager: false },
      'user.clinicInformation': { eager: false },
      'user.specialConditions': { eager: false },
      'user.credentials': { eager: false },
    },
  },
})
@Controller('EmergencyContacts')
@ApiTags('EmergencyContacts')
export class EmergencyContactController
  implements CrudController<EmergencyContact>
{
  constructor(public service: EmergencyContactService) {}

  get base(): CrudController<EmergencyContact> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple EmergencyContacts' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single EmergencyContact' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single EmergencyContact' })
  @ApiBody({
    type: EmergencyContactCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: EmergencyContact
  ) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multipleEmergencyContacts' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<EmergencyContact>
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single EmergencyContact' })
  update(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: EmergencyContact
  ) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single EmergencyContact' })
  replace(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: EmergencyContact
  ) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single EmergencyContact' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
