/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { EmergencyContact } from './EmergencyContact.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { EmergencyContactService } from './EmergencyContact.service';
import { EmergencyContactController } from './EmergencyContact.controller';

@Module({
  imports: [TypeOrmModule.forFeature([EmergencyContact])],
  providers: [EmergencyContactService],
  exports: [EmergencyContactService],
  controllers: [EmergencyContactController],
})
export class EmergencyContactModule {}
