/**
 * This file generated by Apso.
 */
export enum UserStatusEnum {
  Active = 'Active',
  Inactive = 'Inactive',
  Delete = 'Delete',
}
export enum UserRoleEnum {
  admin = 'admin',
  staff = 'staff',
}
export enum CredentialCredentialNameEnum {
  CPR_TRAINING = 'CPR_TRAINING',
  MEDICAL_TRAINING = 'MEDICAL_TRAINING',
  PHYSIOTHERAPY = 'PHYSIOTHERAPY',
}
export enum ClientStatusEnum {
  Current = 'Current',
  Waitlisted = 'Waitlisted',
  Archived = 'Archived',
}
