/**
 * This file generated by Apso.
 */
import { UserModule } from './User/User.module';
import { NoteModule } from './Note/Note.module';
import { staffHourModule } from './staffHour/staffHour.module';
import { ClinicInformationModule } from './ClinicInformation/ClinicInformation.module';
import { SpecialConditionModule } from './SpecialCondition/SpecialCondition.module';
import { CredentialModule } from './Credential/Credential.module';
import { EmergencyContactModule } from './EmergencyContact/EmergencyContact.module';
import { ClientModule } from './Client/Client.module';

export default [
  UserModule,
  NoteModule,
  staffHourModule,
  ClinicInformationModule,
  SpecialConditionModule,
  CredentialModule,
  EmergencyContactModule,
  ClientModule,
];
