/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import {
  SpecialCondition,
  SpecialConditionCreate,
} from './dtos/SpecialCondition.dto';
import { SpecialConditionController } from './SpecialCondition.controller';
import { SpecialConditionService } from './SpecialCondition.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('SpecialConditionController', () => {
  let controller: SpecialConditionController;
  let spyService: SpecialConditionService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: SpecialConditionService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [SpecialConditionController],
      providers: [SpecialConditionService, ApiServiceProvider],
    }).compile();

    controller = module.get<SpecialConditionController>(
      SpecialConditionController
    );
    spyService = module.get<SpecialConditionService>(SpecialConditionService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call SpecialConditionController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call SpecialConditionController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new SpecialCondition();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
