/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import {
  SpecialCondition,
  SpecialConditionCreate,
} from './dtos/SpecialCondition.dto';
import { SpecialConditionService } from './SpecialCondition.service';

@Crud({
  model: {
    type: SpecialCondition,
  },
  dto: {
    create: SpecialConditionCreate,
    update: SpecialCondition,
    replace: SpecialCondition,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
  },
})
@Controller('SpecialConditions')
@ApiTags('SpecialConditions')
export class SpecialConditionController
  implements CrudController<SpecialCondition>
{
  constructor(public service: SpecialConditionService) {}

  get base(): CrudController<SpecialCondition> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple SpecialConditions' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single SpecialCondition' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single SpecialCondition' })
  @ApiBody({
    type: SpecialConditionCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: SpecialCondition
  ) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multipleSpecialConditions' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<SpecialCondition>
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single SpecialCondition' })
  update(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: SpecialCondition
  ) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single SpecialCondition' })
  replace(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: SpecialCondition
  ) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single SpecialCondition' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
