/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { SpecialCondition } from './SpecialCondition.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { SpecialConditionService } from './SpecialCondition.service';
import { SpecialConditionController } from './SpecialCondition.controller';

@Module({
  imports: [TypeOrmModule.forFeature([SpecialCondition])],
  providers: [SpecialConditionService],
  exports: [SpecialConditionService],
  controllers: [SpecialConditionController],
})
export class SpecialConditionModule {}
