/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { staffHour, staffHourCreate } from './dtos/staffHour.dto';
import { staffHourController } from './staffHour.controller';
import { staffHourService } from './staffHour.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('staffHourController', () => {
  let controller: staffHourController;
  let spyService: staffHourService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: staffHourService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [staffHourController],
      providers: [staffHourService, ApiServiceProvider],
    }).compile();

    controller = module.get<staffHourController>(staffHourController);
    spyService = module.get<staffHourService>(staffHourService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call staffHourController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call staffHourController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new staffHour();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
