/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { staffHour } from './staffHour.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { staffHourService } from './staffHour.service';
import { staffHourController } from './staffHour.controller';

@Module({
  imports: [TypeOrmModule.forFeature([staffHour])],
  providers: [staffHourService],
  exports: [staffHourService],
  controllers: [staffHourController],
})
export class staffHourModule {}
