/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import { Credential, CredentialCreate } from './dtos/Credential.dto';
import { CredentialService } from './Credential.service';

@Crud({
  model: {
    type: Credential,
  },
  dto: {
    create: CredentialCreate,
    update: Credential,
    replace: Credential,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
    join: {
      user: { eager: false },
      'user.notes': { eager: false },
      'user.clients': { eager: false },
      'user.clients.associatedStaffs': { eager: false },
      'user.clients.associatedStaffs.notes': { eager: false },
      'user.clients.associatedStaffs.staffHour': { eager: false },
      'user.clients.associatedStaffs.clinicInformation': { eager: false },
      'user.clients.associatedStaffs.emergencyContacts': { eager: false },
      'user.clients.associatedStaffs.specialConditions': { eager: false },
      'user.staffHour': { eager: false },
      'user.clinicInformation': { eager: false },
      'user.emergencyContacts': { eager: false },
      'user.specialConditions': { eager: false },
    },
  },
})
@Controller('Credentials')
@ApiTags('Credentials')
export class CredentialController implements CrudController<Credential> {
  constructor(public service: CredentialService) {}

  get base(): CrudController<Credential> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple Credentials' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single Credential' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single Credential' })
  @ApiBody({
    type: CredentialCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: Credential) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multipleCredentials' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<Credential>
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single Credential' })
  update(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: Credential) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single Credential' })
  replace(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: Credential) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single Credential' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
