/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Credential } from './Credential.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { CredentialService } from './Credential.service';
import { CredentialController } from './Credential.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Credential])],
  providers: [CredentialService],
  exports: [CredentialService],
  controllers: [CredentialController],
})
export class CredentialModule {}
