/**
 * This file generated by Apso.
 */ /* eslint @typescript-eslint/no-unused-vars: "off" */

import {
  Column,
  Entity,
  ManyToOne,
  CreateDateColumn,
  UpdateDateColumn,
  PrimaryGeneratedColumn,
  Generated,
  JoinColumn,
  JoinTable,
  Index,
  Unique,
  PrimaryColumn,
} from 'typeorm';
import {
  IsOptional,
  IsString,
  MaxLength,
  IsNotEmpty,
  IsEmail,
  IsBoolean,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { CrudValidationGroups } from '@nestjsx/crud';
import * as enums from '../enums';
import { User } from '../User/User.entity';

const { CREATE, UPDATE } = CrudValidationGroups;

@Entity('credential')
export class Credential {
  // Fields
  @PrimaryGeneratedColumn()
  id!: number;

  @CreateDateColumn()
  created_at: Date;

  @UpdateDateColumn()
  updated_at: Date;

  @Column({
    type: 'enum',
    enum: enums.CredentialCredentialNameEnum,
    default: enums.CredentialCredentialNameEnum.CPR_TRAINING,
  })
  credentialName!: enums.CredentialCredentialNameEnum;

  @Column({ type: 'date', nullable: true })
  issueDate: string;

  @Column({ type: 'date', nullable: true })
  expireDate: string;

  @IsOptional({ groups: [UPDATE] })
  @Column({ type: 'text', nullable: true })
  note: string;

  // Associations

  @ManyToOne(() => User, (user) => user.credentials)
  @JoinColumn({ name: 'userId' })
  user: User;

  @Column({ type: 'integer', nullable: true })
  userId: number;
}
