/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Credential, CredentialCreate } from './dtos/Credential.dto';
import { CredentialController } from './Credential.controller';
import { CredentialService } from './Credential.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('CredentialController', () => {
  let controller: CredentialController;
  let spyService: CredentialService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: CredentialService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [CredentialController],
      providers: [CredentialService, ApiServiceProvider],
    }).compile();

    controller = module.get<CredentialController>(CredentialController);
    spyService = module.get<CredentialService>(CredentialService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call CredentialController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call CredentialController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Credential();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
