version: '2'

services:
  postgres:
    hostname: postgres
    image: postgres:14.6
    ports:
      - $DATABASE_PORT
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      PGDATA: /tmp
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./containers/postgres/data:/var/lib/postgresql/data
      - ./containers/postgres/postgres.conf:/etc/postgresql/postgresql.conf