import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class NotesCreate {
  @ApiProperty()
  issue_date: string;
  @ApiProperty()
  label: string;
  @ApiProperty()
  note: string;
  @ApiProperty()
  file_url: string;
  @ApiProperty()
  userId: number;
}

export class Notes {
  @ApiProperty()
  id: number;
  @ApiProperty()
  issue_date: string;
  @ApiProperty()
  label: string;
  @ApiProperty()
  note: string;
  @ApiProperty()
  file_url: string;
  @ApiProperty()
  userId: number;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
