import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */
import * as enums from '../../enums';

export class UserCreate {
  @ApiProperty()
  email: string;
  @ApiProperty()
  firstName: string;
  @ApiProperty()
  lastName: string;
  @ApiProperty()
  clerkId: string;
  @ApiProperty()
  status: enums.UserStatusEnum;
  @ApiProperty()
  role: enums.UserRoleEnum;
  @ApiProperty()
  primary_phone: string;
  @ApiProperty()
  signature: string;
  @ApiProperty()
  title: string;
  @ApiProperty()
  bio: string;
  @ApiProperty()
  address1: string;
  @ApiProperty()
  address2: string;
  @ApiProperty()
  city: string;
  @ApiProperty()
  state: string;
  @ApiProperty()
  zip_code: number;
  @ApiProperty()
  date_of_birth: string;
  @ApiProperty()
  gender: string;
  @ApiProperty()
  work_phone: string;
  @ApiProperty()
  home_phone: string;
  @ApiProperty()
  social_security_number: string;
  @ApiProperty()
  image_url: string;
}

export class User {
  @ApiProperty()
  id: number;
  @ApiProperty()
  email: string;
  @ApiProperty()
  firstName: string;
  @ApiProperty()
  lastName: string;
  @ApiProperty()
  clerkId: string;
  @ApiProperty()
  status: enums.UserStatusEnum;
  @ApiProperty()
  role: enums.UserRoleEnum;
  @ApiProperty()
  primary_phone: string;
  @ApiProperty()
  signature: string;
  @ApiProperty()
  title: string;
  @ApiProperty()
  bio: string;
  @ApiProperty()
  address1: string;
  @ApiProperty()
  address2: string;
  @ApiProperty()
  city: string;
  @ApiProperty()
  state: string;
  @ApiProperty()
  zip_code: number;
  @ApiProperty()
  date_of_birth: string;
  @ApiProperty()
  gender: string;
  @ApiProperty()
  work_phone: string;
  @ApiProperty()
  home_phone: string;
  @ApiProperty()
  social_security_number: string;
  @ApiProperty()
  image_url: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
