import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class NoteCreate {
  @ApiProperty()
  issue_date: string;
  @ApiProperty()
  label: string;
  @ApiProperty()
  note: string;
  @ApiProperty()
  file_url: string;
  @ApiProperty()
  attachments: JSON;
  @ApiProperty()
  userId: number;
}

export class Note {
  @ApiProperty()
  id: number;
  @ApiProperty()
  issue_date: string;
  @ApiProperty()
  label: string;
  @ApiProperty()
  note: string;
  @ApiProperty()
  file_url: string;
  @ApiProperty()
  attachments: JSON;
  @ApiProperty()
  userId: number;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
