import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class staffHourCreate {
  @ApiProperty()
  expectedHours: number;
  @ApiProperty()
  maxHours: number;
  @ApiProperty()
  maxOvertimeHours: number;
  @ApiProperty()
  supervisedHours: number;
  @ApiProperty()
  vacationTimeAlloted: number;
  @ApiProperty()
  sickTimeAlloted: number;
}

export class staffHour {
  @ApiProperty()
  id: number;
  @ApiProperty()
  expectedHours: number;
  @ApiProperty()
  maxHours: number;
  @ApiProperty()
  maxOvertimeHours: number;
  @ApiProperty()
  supervisedHours: number;
  @ApiProperty()
  vacationTimeAlloted: number;
  @ApiProperty()
  sickTimeAlloted: number;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
