/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { StaffHours, StaffHoursCreate } from './dtos/StaffHours.dto';
import { StaffHoursController } from './StaffHours.controller';
import { StaffHoursService } from './StaffHours.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('StaffHoursController', () => {
  let controller: StaffHoursController;
  let spyService: StaffHoursService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: StaffHoursService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [StaffHoursController],
      providers: [StaffHoursService, ApiServiceProvider],
    }).compile();

    controller = module.get<StaffHoursController>(StaffHoursController);
    spyService = module.get<StaffHoursService>(StaffHoursService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call StaffHoursController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call StaffHoursController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new StaffHours();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
