/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { StaffHours } from './StaffHours.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { StaffHoursService } from './StaffHours.service';
import { StaffHoursController } from './StaffHours.controller';

@Module({
  imports: [TypeOrmModule.forFeature([StaffHours])],
  providers: [StaffHoursService],
  exports: [StaffHoursService],
  controllers: [StaffHoursController],
})
export class StaffHoursModule {}
