import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class EmergencyContactCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  relationship: string;
  @ApiProperty()
  phone: string;
  @ApiProperty()
  email: string;
  @ApiProperty()
  address: string;
  @ApiProperty()
  userId: number;
}

export class EmergencyContact {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  relationship: string;
  @ApiProperty()
  phone: string;
  @ApiProperty()
  email: string;
  @ApiProperty()
  address: string;
  @ApiProperty()
  userId: number;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
